spring:
  application:
    name: elastic-monitor
  mail:
    host: localhost
    port: 25
    username: omnifit-monitor
    password:
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
logging:
  config: classpath:logback-spring.xml


